import type { HvyDocumentSearchMode, SearchFilterMode } from '../../../heavy-file-format/src/search/types';
import { type AiSettings, type AppSettings, type DocumentCreationType, type McpClientInstallTarget, type McpSettings, type TemplateExtension, type TemplateScope, type WorkspaceTemplateVisibility } from '../backend';
import type { HvyMode } from '../hvy';
import { type AppState } from '../state';

export interface UiHandlers {
  newWorkspace(): void;
  openWorkspaceManager(): void;
  closeWorkspaceManager(): void;
  reorderWorkspace(draggedPath: string, targetPath: string, before: boolean): void;
  sortWorkspaceOrder(order: 'nameAsc' | 'nameDesc' | 'recentDesc' | 'recentAsc'): void;
  renameWorkspace(path: string, name: string): void;
  archiveWorkspace(path: string): void;
  unarchiveWorkspace(path: string): void;
  setWorkspaceHiddenFromAI(workspacePath: string, hiddenFromAI: boolean): void;
  setWorkspaceFolderHiddenFromAI(workspacePath: string, targetDirectory: string, hiddenFromAI: boolean): void;
  setEncryptedFolderAIAllowed(workspacePath: string, targetDirectory: string, name: string, allowed: boolean): void;
  setEncryptedFileAIAllowed(workspacePath: string, path: string, name: string, allowed: boolean): void;
  confirmEncryptedAIAccess(): void;
  cancelEncryptedAIAccess(): void;
  toggleWorkspaceActions(path: string): void;
  setIntegrationsSectionExpanded(expanded: boolean): void;
  setWorkspacesSectionExpanded(expanded: boolean): void;
  closeWorkspaceActions(): void;
  createWorkspace(name: string, location: 'managed' | 'choose'): void;
  confirmWorkspaceInitialization(): void;
  cancelWorkspaceInitialization(): void;
  setNewWorkspaceLocation(location: 'managed' | 'choose'): void;
  cancelNewWorkspace(): void;
  openNewFolder(workspacePath: string, parentDirectory?: string, encrypted?: boolean): void;
  createWorkspaceFolder(workspacePath: string, parentDirectory: string, name: string, encrypted: boolean): void;
  cancelNewFolder(): void;
  newDocumentInWorkspace(workspacePath: string, targetDirectory?: string): void;
  setNewDocumentType(type: DocumentCreationType): void;
  createDocumentInWorkspace(name: string, templateId: string, targetDirectory?: string): void;
  cancelNewDocument(): void;
  openImportInWorkspace(workspacePath: string, targetDirectory?: string): void;
  setImportDocumentType(type: DocumentCreationType): void;
  openImportIntoCurrent(): void;
  setImportSourceTab(tab: 'workspace' | 'anywhere'): void;
  setImportOutputMode(mode: 'current' | 'workspace'): void;
  updateImportExcludeTags(tags: string): void;
  updateImportSourceText(text: string): void;
  setImportNewSectionsOnly(newSectionsOnly: boolean): void;
  selectImportWorkspaceSource(path: string): void;
  chooseImportSource(): void;
  createImportedDocument(name: string, templateId: string, instructions: string, pastedSourceText: string, excludeTags: string, newSectionsOnly: boolean, targetDirectory?: string): void;
  importIntoCurrent(instructions: string, pastedSourceText: string, excludeTags: string, newSectionsOnly: boolean, outputMode: 'current' | 'workspace', outputName: string): void;
  cancelImport(): void;
  addFilesToWorkspace(workspacePath: string, targetDirectory?: string): void;
  addDroppedFilesToWorkspace(workspacePath: string, files: File[], targetDirectory?: string): void;
  deleteWorkspaceFolder(workspacePath: string, targetDirectory: string): void;
  renameEncryptedFolder(workspacePath: string, targetDirectory: string, currentName: string): void;
  submitRenameEncryptedFolder(name: string): void;
  cancelRenameEncryptedFolder(): void;
  confirmDeleteWorkspaceFolder(workspacePath: string, targetDirectory: string, folderName: string, archivedFiles: string[]): void;
  cancelDeleteWorkspaceFolder(): void;
  openWorkspaceFilter(workspacePath: string, targetDirectory?: string): void;
  openWorkspaceChat(workspacePath: string, targetDirectory?: string): void;
  toggleWorkspaceEmbeddingPreview(workspacePath: string): void;
  closeWorkspaceChat(): void;
  saveWorkspaceChat(): void;
  discardWorkspaceChat(): void;
  cancelCloseWorkspaceChat(): void;
  cancelWorkspaceChatIndexing(): void;
  openWorkspaceLink(href: string): void;
  updateWorkspaceChatDraft(value: string): void;
  submitWorkspaceChat(): void;
  setWorkspaceFileView(workspacePath: string, view: AppState['workspaceFileViews'][string]): void;
  setWorkspaceExpanded(workspacePath: string, expanded: boolean): void;
  setWorkspaceFolderExpanded(workspacePath: string, relativePath: string, expanded: boolean): void;
  closeWorkspaceFilter(): void;
  setWorkspaceFilterMode(mode: HvyDocumentSearchMode): void;
  setWorkspaceFilterBehavior(mode: SearchFilterMode): void;
  updateWorkspaceFilterQuery(query: string): void;
  submitWorkspaceFilter(): void;
  clearWorkspaceFilter(): void;
  openAbout(): void;
  openIntegrations(): void;
  closeIntegrations(): void;
  openIntegration(destination: 'msn' | 'gmail' | 'calendar'): void;
  openIntegrationPage(integrationId: string, pageId: string, profileId?: string): void;
  openIntegrationReadyChecks(integrationId: string, pageId: string): void;
  cancelIntegrationReadyChecks(): void;
  cancelIntegrationReadyCheckSelection(): void;
  requestIntegrationReadyCheck(integrationId: string, pageId: string, urlMode: import('../integrationRegistry').IntegrationPageReadyChecks['urlMode'], urlValue: string, expectedValues: Record<string, string>): void;
  completeIntegrationReadyCheck(value: unknown): void;
  testIntegrationReadyChecks(integrationId: string, pageId: string, urlMode: import('../integrationRegistry').IntegrationPageReadyChecks['urlMode'], urlValue: string, expectedValues: Record<string, string>): void;
  completeIntegrationReadyCheckValidation(value: unknown): void;
  removeIntegrationReadyCheck(checkId: string): void;
  saveIntegrationReadyChecks(integrationId: string, pageId: string, urlMode: import('../integrationRegistry').IntegrationPageReadyChecks['urlMode'], urlValue: string, expectedValues: Record<string, string>): void;
  setIntegrationQuickViewProfile(integrationId: string, pageId: string, profileId: string, visible: boolean): void;
  addActionForIntegrationPage(integrationId: string, pageId: string): void;
  editIntegrationAction(integrationId: string, actionId: string): void;
  closeIntegrationActionBuilder(): void;
  cancelDiscardIntegrationAction(): void;
  confirmDiscardIntegrationAction(): void;
  cancelIntegrationActionSelection(): void;
  addAnotherIntegrationActionExample(parentIndex?: number, fieldIndex?: number | null): void;
  addIntegrationActionAnchor(): void;
  testIntegrationActionPattern(): void;
  previewIntegrationAction(): void;
  updateIntegrationTargetLabel(index: number, label: string): void;
  updateIntegrationActionDraftName(name: string): void;
  updateIntegrationActionDraftDescription(description: string): void;
  updateIntegrationTargetCardinality(index: number, cardinality: 'single' | 'list'): void;
  updateIntegrationTargetOptional(index: number, optional: boolean): void;
  setIntegrationTargetAbsent(fieldIndex: number, parentIndex: number, absent: boolean): void;
  selectIntegrationActionExample(index: number): void;
  updateIntegrationActionMinimumConfidence(value: number): void;
  continueIntegrationActionBuilder(): void;
  backIntegrationActionBuilder(): void;
  reviewIntegrationActionRequest(name: string, description: string): void;
  saveIntegrationActionDraft(): void;
  runIntegrationAction(integrationId: string, actionId: string): void;
  closeIntegrationActionResult(): void;
  addCommandForIntegrationAction(integrationId: string, actionId: string): void;
  addCommandForIntegrationPage(integrationId: string, pageId: string): void;
  cancelIntegrationCommandBuilder(): void;
  saveIntegrationCommand(name: string, inputNames: Record<string, string>): void;
  requestDeleteIntegrationCommand(integrationId: string, actionId: string, commandId: string): void;
  cancelDeleteIntegrationCommand(): void;
  confirmDeleteIntegrationCommand(): void;
  runIntegrationCommand(integrationId: string, actionId: string, commandId: string, recordParent?: string): void;
  runIntegrationPageCommand(integrationId: string, pageId: string, commandId: string): void;
  cancelIntegrationCommandRun(): void;
  submitIntegrationCommandRun(inputs: Record<string, string>): void;
  requestDeleteIntegrationAction(integrationId: string, actionId: string): void;
  cancelDeleteIntegrationAction(): void;
  confirmDeleteIntegrationAction(): void;
  reviewIntegrationActionSelection(kind: 'target' | 'example', index: number): void;
  removeIntegrationActionSelection(kind: 'target' | 'example', index: number): void;
  selectIntegration(integrationId: string): void;
  selectIntegrationProfile(profileId: string): void;
  requestAddIntegrationProfile(): void;
  cancelAddIntegrationProfile(): void;
  addIntegrationProfile(name: string): void;
  requestAddIntegrationPage(): void;
  cancelAddIntegrationPage(): void;
  addIntegrationPage(name: string, url: string): void;
  discoverIntegrationSources(integrationId: string, pageId: string): void;
  saveIntegrationSource(integrationId: string, pageId: string, source: import('../integrationBrowser').IntegrationStructuredSource): void;
  fetchIntegrationSource(integrationId: string, pageId: string, sourceId: string): void;
  closeIntegrationStructuredResult(): void;
  setInspectionPrivacyRule(path: string, action: 'label' | 'remove' | 'keep', label?: string): void;
  updateInspectionPrivacyLabel(path: string, label: string): void;
  controlIntegrationBrowser(command: 'back' | 'forward' | 'reload' | 'inspect' | 'close'): void;
  probeIntegrationStorage(): void;
  requestResetIntegrationVault(): void;
  confirmResetIntegrationVault(): void;
  cancelResetIntegrationVault(): void;
  chooseDocumentKeyFiles(): void;
  confirmImportDocumentKeys(): void;
  cancelImportDocumentKeys(): void;
  exportDocumentKey(keyId: string): void;
  requestDeleteDocumentKey(keyId: string): void;
  confirmDeleteDocumentKey(): void;
  cancelDeleteDocumentKey(): void;
  openDocumentKeyManager(): void;
  closeDocumentKeyManager(): void;
  requestDocumentEncryption(action: 'encrypt' | 'decrypt'): void;
  confirmDocumentEncryption(): void;
  cancelDocumentEncryption(): void;
  closeAbout(): void;
  openDebugLog(): void;
  closeDebugLog(): void;
  refreshDebugLog(): void;
  clearDebugLog(): void;
  saveDebugLogSettings(settings: AppSettings): void;
  openAppSettings(): void;
  openPluginManager(): void;
  installPluginFiles(files: File[], settings: AppSettings): void;
  openHomepagePicker(settings: AppSettings): void;
  useCurrentDocumentAsHomepage(settings: AppSettings): void;
  chooseReplacementHomepage(): void;
  cancelHomepagePicker(): void;
  selectHomepageDocument(path: string): void;
  useIncludedGuideAsHomepage(): void;
  disableHomepage(): void;
  saveAppSettings(settings: AppSettings): void;
  cancelAppSettings(settings?: AppSettings): void;
  discardAppSettingsChanges(): void;
  keepEditingAppSettings(): void;
  openScriptingReview(): void;
  closeScriptingReview(): void;
  setWholeFilePowerScriptingAllowed(path: string, allowed: boolean): void;
  revokePowerScriptAcceptance(path: string, fingerprint: string): void;
  openAiSettings(): void;
  selectAiProvider(providerId: string, settings: AiSettings): void;
  setDefaultAiProvider(settings: AiSettings): void;
  openProviderDocs(url: string): void;
  saveAiSettings(settings: AiSettings): void;
  cancelAiSettings(settings?: AiSettings): void;
  discardAiSettingsChanges(): void;
  keepEditingAiSettings(): void;
  openMcpSettings(): void;
  saveMcpSettings(settings: McpSettings): void;
  cancelMcpSettings(settings?: McpSettings): void;
  discardMcpSettingsChanges(): void;
  keepEditingMcpSettings(): void;
  startMcpServer(): void;
  stopMcpServer(): void;
  restartMcpServer(): void;
  installMcpClient(target: McpClientInstallTarget): void;
  removeMcpClient(target: McpClientInstallTarget): void;
  restoreMcpClientBackup(target: McpClientInstallTarget): void;
  copyMcpConnectionUrl(url: string): void;
  copyMcpBearerToken(token: string): void;
  copyMcpSetupValue(value: string, label: string): void;
  openColorTheme(): void;
  openDocumentColorTheme(): void;
  closeColorTheme(): void;
  updateColorThemeName(name: string): void;
  setDocumentColorsEnabled(enabled: boolean): void;
  saveColorTheme(): void;
  exportColorTheme(): void;
  importColorTheme(): void;
  selectColorTheme(id: string): void;
  deleteColorTheme(id: string): void;
  updateColorTheme(name: string, value: string): void;
  resetColorTheme(name: string): void;
  applyColorThemePalette(id: string | null): void;
  restoreBackup(id: string): void;
  discardBackup(id: string): void;
  cancelRecovery(): void;
  openVersionHistory(): void;
  selectSavedVersion(id: string): void;
  closeVersionHistory(): void;
  cancelCloseDocument(): void;
  confirmSaveConflict(): void;
  cancelSaveConflict(): void;
  saveBeforeWorkspaceFileOperation(): void;
  discardBeforeWorkspaceFileOperation(): void;
  cancelWorkspaceFileOperation(): void;
  closeDocumentWithoutSaving(): void;
  discardCloseDocumentDraft(): void;
  reviewCloseDocumentLater(): void;
  saveAndCloseApp(): void;
  closeAppWithoutSaving(): void;
  cancelAppClose(): void;
  selectDocumentTab(path: string): void;
  closeDocumentTab(path: string): void;
  cycleTabStack(direction: 1 | -1): void;
  commitTabStack(): void;
  cancelTabStack(): void;
  openWorkspace(): void;
  openFile(): void;
  openRecentWorkspace(path: string): void;
  openRecentFile(path: string): void;
  selectFile(path: string): void;
  refreshWorkspace(path: string): void;
  unlockEncryptedFolders(path: string): void;
  retryWorkspace(path: string): void;
  showFileInFolder(path: string): void;
  renameFile(path: string, currentName: string): void;
  archiveFile(path: string, currentName: string): void;
  restoreFile(path: string, currentName: string): void;
  setFileLocked(path: string, currentName: string, locked: boolean): void;
  setFileHiddenFromAI(path: string, currentName: string, hiddenFromAI: boolean): void;
  confirmDeleteFile(path: string, currentName: string): void;
  deleteFile(): void;
  cancelDeleteFile(): void;
  copyWorkspaceFile(path: string, currentName: string): void;
  cutWorkspaceFile(path: string, currentName: string): void;
  pasteWorkspaceClipboard(workspacePath: string, targetDirectory?: string): void;
  copyFileToWorkspace(path: string, currentName: string): void;
  moveFileToWorkspace(path: string, currentName: string): void;
  moveWorkspaceFileToFolder(path: string, workspacePath: string, targetDirectory?: string): void;
  convertWorkspaceFileKind(path: string, workspacePath: string, toTemplate: boolean): void;
  submitRenameFile(name: string): void;
  cancelRenameFile(): void;
  saveCurrentToWorkspace(): void;
  submitWorkspaceTransfer(workspacePath: string, name: string, targetDirectory?: string): void;
  cancelWorkspaceTransfer(): void;
  setMode(mode: HvyMode): void;
  openDocumentMeta(): void;
  save(): void;
  saveAs(): void;
  setSaveAsKind(kind: AppState['saveAsKind']): void;
  setSaveAsScope(scope: 'workspace' | 'anywhere'): void;
  saveAsToWorkspace(workspacePath: string, name: string, targetDirectory?: string): void;
  saveAsAnywhere(): void;
  cancelSaveAs(): void;
  closeDocument(): void;
  saveAndCloseDocument(): void;
  openSaveTemplate(): void;
  exportPdf(): void;
  openExportedPdf(): void;
  revealExportedPdf(): void;
  closeExportedPdfDialog(): void;
  saveBeforeExportPdf(): void;
  cancelExportPdfSavePrompt(): void;
  setSaveTemplateScope(scope: TemplateScope): void;
  saveAsTemplate(name: string, scope: TemplateScope, extension: TemplateExtension): void;
  cancelSaveTemplate(): void;
  saveWorkspaceTemplateVisibility(workspacePath: string, visibility: WorkspaceTemplateVisibility): void;
  createFile(): void;
  zoomAppIn(): void;
  zoomAppOut(): void;
  resetAppZoom(): void;
  zoomDocumentIn(): void;
  zoomDocumentOut(): void;
  resetDocumentZoom(): void;
}
